spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xbyy_game?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: admin
    password: test123456
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 127.0.0.1:8848
  application:
    name: chat
  #redis配置
  redis:
    host: 127.0.0.1
    password: testupload
    port: 6379
    database: 0

mybatis-plus:
  type-aliases-package: com.xbyy.gamechat.pojo.entity
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 9001